base_link: 'base_footprint'

# =====================================================
left:
    # could also be <side>_eef
    end_effector_name: 'left_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['l_gripper_l_finger_joint']

    #open position
    pregrasp_posture : [0.0095]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [-0.0125]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0.05, 0, 0.12]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 3.14] # 1.5707 = PI/2

    end_effector_parent_link: 'l_wrist_roll_link'
# =====================================================
right:
    end_effector_name: 'right_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['r_gripper_l_finger_joint']

    #open position
    pregrasp_posture : [0.0095]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [-0.0125]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0.05, 0, 0.12]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 3.14] # 1.5707 = PI/2

    end_effector_parent_link: 'r_wrist_roll_link'

