#
# A request / response pair for the central IK manager. Allows multiple types
# of request types and returns an array of one or more results on success.
#

# REQUIRED - the type of configuration request
# See Movement.msg for constants - for some reason defining them here does
# not properly work or get defined when linking.
string type

# OPTIONAL - only required if type is set to POSE
trooper_msgs/PoseRequest pose_request

# OPTIONAL - only required if type is set to DIRECTION
trooper_msgs/DirectionRequest direction_request

# OPTIONAL - only required if type is set to TRAJECTORY
trooper_msgs/TrajectoryRequest trajectory_request

# OPTIONAL - set the robot state IK is solved in
moveit_msgs/RobotState robot_state

---

# the error code returned by the IK solver used
moveit_msgs/MoveItErrorCodes error_code

# an explanation of the error code
string reason

# each response encapsulates joint names and positons
# one result for pose or direction request
# <n> for trajectory request of size n
trooper_msgs/JointRequest[] solutions

