CHALLENGE_SUCCESS = 'complete'
CHALLENGE_FAILURE = 'failure'

START_POSE_SUCCESS = 'success'
START_POSE_FAILURE = 'failure'

FIND_SHELF_SUCCESS = 'success'
FIND_SHELF_FAILURE = 'failure'

UPDATE_PLAN_NEXT_OBJECT = 'next_object'
UPDATE_PLAN_RELOCALIZE_SHELF = 'relocalize_shelf'
UPDATE_PLAN_NO_MORE_OBJECTS = 'no_more_objects'
UPDATE_PLAN_FAILURE = 'failure'

MOVE_TO_BIN_SUCCESS = 'success'
MOVE_TO_BIN_FAILURE = 'failure'

SENSE_BIN_SUCCESS = 'success'
SENSE_BIN_NO_OBJECTS = 'no_objects'
SENSE_BIN_FAILURE = 'failure'

GRASP_SUCCESS = 'success'
GRASP_FAILURE = 'failure'

EXTRACT_ITEM_SUCCESS = 'success'
EXTRACT_ITEM_FAILURE = 'failure'

DROP_OFF_ITEM_SUCCESS = 'success'
DROP_OFF_ITEM_FAILURE = 'failure'
