CHALLENGE_SUCCESS = 'complete'
CHALLENGE_FAILURE = 'failure'

START_POSE_SUCCESS = 'success'
START_POSE_FAILURE = 'failure'

FIND_SHELF_SUCCESS = 'success'
FIND_SHELF_FAILURE = 'failure'

UPDATE_PLAN_NEXT_OBJECT = 'next_object'
UPDATE_PLAN_RELOCALIZE_SHELF = 'relocalize_shelf'
UPDATE_PLAN_NO_MORE_OBJECTS = 'no_more_objects'
UPDATE_PLAN_FAILURE = 'failure'

MOVE_TO_BIN_SUCCESS = 'success'
MOVE_TO_BIN_FAILURE = 'failure'

SENSE_BIN_SUCCESS = 'success'
SENSE_BIN_NO_OBJECTS = 'no_objects'
SENSE_BIN_FAILURE = 'failure'

GRASP_TOOL_SUCCESS = 'success'
GRASP_TOOL_FAILURE = 'failure'

RELEASE_TOOL_SUCCESS = 'success'
RELEASE_TOOL_FAILURE = 'failure'

GRASP_SUCCESS = 'success'
GRASP_FAILURE = 'failure'
GRASP_NONE = 'no_grasps'

EXTRACT_ITEM_SUCCESS = 'success'
EXTRACT_ITEM_FAILURE = 'failure'

VERIFY_GRASP_SUCCESS = 'success'
VERIFY_GRASP_FAILURE = 'failure'
VERIFY_GRASP_RETRY = 'retry'

DROP_OFF_ITEM_SUCCESS = 'success'
DROP_OFF_ITEM_FAILURE = 'failure'

CAPTURE_ITEM_NEXT = 'next'
CAPTURE_ITEM_DONE = 'done'

GATHER_DATA_NEXT = 'next'
GATHER_DATA_DONE = 'done'

GRASP_PLAN_SUCCESS = 'success'
GRASP_PLAN_NONE = 'no_grasps'
GRASP_PLAN_FAILURE = 'failure'
GRASP_MOVE_OBJECT = 'move_object'

MOVE_OBJECT_SUCCESS = 'success'
MOVE_OBJECT_FAILURE = 'failure'

EXPLORATION_SUCCESS = 'EXPLORATION_SUCCESS'
EXPLORATION_FAILURE = 'EXPLORATION_FAILURE'
INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS'
INITIALIZE_FAILURE = 'INITIALIZE_FAILURE'
SENSE_OBJECT_BEFORE_SUCCESS = 'SENSE_OBJECT_BEFORE_SUCCESS'
SENSE_OBJECT_AFTER_SUCCESS = 'SENSE_OBJECT_AFTER_SUCCESS'
SENSE_OBJECT_FAILURE = 'SENSE_OBJECT_FAILURE'
TOOL_EXPLORATION_SUCCESS = 'TOOL_EXPLORATION_SUCCESS'
TOOL_EXPLORATION_FAILURE = 'TOOL_EXPLORATION_FAILURE'

EXPERIMENT_SUCCESS = 'EXPERIMENT_SUCCESS'
EXPERIMENT_FAILURE = 'EXPERIMENT_FAILURE'

PLAN_SUCCESS = 'EXPERIMENT_SUCCESS'
PLAN_FAILURE = 'EXPERIMENT_FAILURE'